-- -- @CASE keyword
-- SELECT amount_billed,
--   CASE
--     WHEN amount_billed > 30 THEN 'Good Day'
--     WHEN amount_billed > 15 THEN 'Normal Day'
--     ELSE 'Bad Day'
--   END
-- FROM orders;
-- -- @CASE keyword with more specificity 
-- SELECT amount_billed,
--   CASE
--     WHEN amount_billed > 15
--     AND amount_billed <= 30 THEN 'Normal Day'
--     WHEN amount_billed > 30 THEN 'Good Day'
--     ELSE 'Bad Day'
--   END
-- FROM orders;